# docker/Dockerfile.transformer
FROM python:3.11-slim

WORKDIR /app

COPY req.txt .
RUN pip install --no-cache-dir --default-timeout=1000  --retries 10 -r req.txt

COPY src/transformer_api.py .
COPY models/enhanced_multilingual_model ./models/enhanced_multilingual_model

EXPOSE 8020

CMD ["uvicorn", "transformer_api:app", "--host", "0.0.0.0", "--port", "8020"]
